// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteItauCorretora.Infrastructure.Persistence;

#nullable disable

namespace TesteItauCorretora.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HistoricoValorMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoValorMensal");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendacao");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Custodia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("Custodias");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustodiaFilhoteId")
                        .HasColumnType("int");

                    b.Property<int?>("CustodiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.EventoIR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PublicadoKafka")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorIR")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("EventosIR");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CestaRecomendacaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CestaRecomendacaoId");

                    b.ToTable("ItensCesta");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoMercado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TickerComprado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TickerVendido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Rebalanceamentos");
                });

            modelBuilder.Entity("HistoricoValorMensal", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.Cliente", "Cliente")
                        .WithMany("HistoricoValores")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.Cliente", null)
                        .WithMany("ContasGraficas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.Custodia", null)
                        .WithMany("Distribuicao")
                        .HasForeignKey("CustodiaId");

                    b.HasOne("TesteItauCorretora.Domain.Entities.OrdemCompra", null)
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.EventoIR", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.Cliente", null)
                        .WithMany("EventosIR")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.ItemCesta", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.CestaRecomendacao", "CestaRecomendacao")
                        .WithMany("Itens")
                        .HasForeignKey("CestaRecomendacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CestaRecomendacao");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Rebalanceamento", b =>
                {
                    b.HasOne("TesteItauCorretora.Domain.Entities.Cliente", null)
                        .WithMany("Rebalanceamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContasGraficas");

                    b.Navigation("EventosIR");

                    b.Navigation("HistoricoValores");

                    b.Navigation("Rebalanceamentos");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.Custodia", b =>
                {
                    b.Navigation("Distribuicao");
                });

            modelBuilder.Entity("TesteItauCorretora.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
